update

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,7 @@ jobs:
         run: |
           echo "⚠️ Installing dependencies for Client..."
           cd /home/marcmadeit/htdocs/mmi.marccode.com/client
-          npm install --legacy-peer-deps || { echo "❌ npm install failed"; exit 1; }
+          npm ci || { echo "❌ npm install failed"; exit 1; }
 
       - name: 📦 Install dependencies (API)
         run: |
